export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"

export const GET_ORDER_BY_USER_REQUEST = "GET_ORDER_BY_USER_REQUEST"
export const GET_ORDER_BY_USER_SUCCESS = "GET_ORDER_BY_USER_SUCCESS"
export const GET_ORDER_BY_USER_FAILURE = "GET_ORDER_BY_USER_FAILURE"

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST"
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS"
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE"

export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST"
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS"
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE"

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST"
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS"
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE"