export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"

export const GET_ORDER_BY_USER_REQUEST = "GET_ORDER_BY_USER_REQUEST"
export const GET_ORDER_BY_USER_SUCCESS = "GET_ORDER_BY_USER_SUCCESS"
export const GET_ORDER_BY_USER_FAILURE = "GET_ORDER_BY_USER_FAILURE"
