export const GET_PAYMENT_INFO_REQUEST = 'GET_PAYMENT_INFO_REQUEST'
export const GET_PAYMENT_INFO_SUCCESS = 'GET_PAYMENT_INFO_SUCCESS'
export const GET_PAYMENT_INFO_FAILURE = 'GET_PAYMENT_INFO_FAILURE'