export const CREATE_FOOD_REQUEST = "CREATE_FOOD_REQUEST"
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS"
export const CREATE_FOOD_FAILURE = "CREATE_FOOD_FAILURE"

export const UPDATE_FOOD_REQUEST = "UPDATE_FOOD_REQUEST"
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS"
export const UPDATE_FOOD_FAILURE = "UPDATE_FOOD_FAILURE"

export const DELETE_FOOD_REQUEST = "DELETE_FOOD_REQUEST"
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS"
export const DELETE_FOOD_FAILURE = "DELETE_FOOD_FAILURE"

export const UPDATE_FOOD_STATUS_REQUEST = "UPDATE_FOOD_STATUS_REQUEST"
export const UPDATE_FOOD_STATUS_SUCCESS = "UPDATE_FOOD_STATUS_SUCCESS"
export const UPDATE_FOOD_STATUS_FAILURE = "UPDATE_FOOD_STATUS_FAILURE"

export const GET_FOOD_BY_ID_REQUEST = "GET_FOOD_BY_ID_REQUEST"
export const GET_FOOD_BY_ID_SUCCESS = "GET_FOOD_BY_ID_SUCCESS"
export const GET_FOOD_BY_ID_FAILURE = "GET_FOOD_BY_ID_FAILURE"

export const GET_FOOD_BY_RESTAURANT_ID_REQUEST = "GET_FOOD_BY_RESTAURANT_ID_REQUEST"
export const GET_FOOD_BY_RESTAURANT_ID_SUCCESS = "GET_FOOD_BY_RESTAURANT_ID_SUCCESS"
export const GET_FOOD_BY_RESTAURANT_ID_FAILURE = "GET_FOOD_BY_RESTAURANT_ID_FAILURE"

export const GET_FOOD_BY_SEARCH_REQUEST = "GET_FOOD_BY_SEARCH_REQUEST"
export const GET_FOOD_BY_SEARCH_SUCCESS = "GET_FOOD_BY_SEARCH_SUCCESS"
export const GET_FOOD_BY_SEARCH_FAILURE = "GET_FOOD_BY_SEARCH_FAILURE"

export const GET_FOOD_BY_SEARCH_AND_FILTER_REQUEST = "GET_FOOD_BY_SEARCH_AND_FILTER_REQUEST"
export const GET_FOOD_BY_SEARCH_AND_FILTER_SUCCESS = "GET_FOOD_BY_SEARCH_AND_FILTER_SUCCESS"
export const GET_FOOD_BY_SEARCH_AND_FILTER_FAILURE = "GET_FOOD_BY_SEARCH_AND_FILTER_FAILURE"