export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST"
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS"
export const ADD_ITEM_TO_CART_FAILURE = "ADD_ITEM_TO_CART_REQUEST"

export const GET_CART_BY_USER_ID_REQUEST = "GET_CART_BY_USER_ID_REQUEST"
export const GET_CART_BY_USER_ID_SUCCESS = "GET_CART_BY_USER_ID_SUCCESS"
export const GET_CART_BY_USER_ID_FAILURE = "GET_CART_BY_USER_ID_REQUEST"

export const UPDATE_CART_ITEM_QUANTITY_REQUEST = "UPDATE_CART_ITEM_QUANTITY_REQUEST"
export const UPDATE_CART_ITEM_QUANTITY_SUCCESS = "UPDATE_CART_ITEM_QUANTITY_SUCCESS"
export const UPDATE_CART_ITEM_QUANTITY_FAILURE = "UPDATE_CART_ITEM_QUANTITY_FAILURE"

export const REMOVE_CART_ITEM_FROM_CART_REQUEST = "REMOVE_CART_ITEM_FROM_CART_REQUEST"
export const REMOVE_CART_ITEM_FROM_CART_SUCCESS = "REMOVE_CART_ITEM_FROM_CART_SUCCESS"
export const REMOVE_CART_ITEM_FROM_CART_FAILURE = "REMOVE_CART_ITEM_FROM_CART_FAILURE"