export const CREATE_FOOD_CATEGORY_REQUEST = "CREATE_FOOD_CATEGORY_REQUEST";
export const CREATE_FOOD_CATEGORY_SUCCESS = "CREATE_FOOD_CATEGORY_SUCCESS";
export const CREATE_FOOD_CATEGORY_FAILURE = "CREATE_FOOD_CATEGORY_FAILURE";

export const GET_FOOD_CATEGORY_BY_ID_REQUEST = "GET_FOOD_CATEGORY_BY_ID_REQUEST";
export const GET_FOOD_CATEGORY_BY_ID_SUCCESS = "GET_FOOD_CATEGORY_BY_ID_SUCCESS";
export const GET_FOOD_CATEGORY_BY_ID_FAILURE = "GET_FOOD_CATEGORY_BY_ID_FAILURE";

export const GET_FOOD_CATEGORY_BY_RESTAURANT_ID_REQUEST = "GET_FOOD_CATEGORY_BY_RESTAURANT_ID_REQUEST";
export const GET_FOOD_CATEGORY_BY_RESTAURANT_ID_SUCCESS = "GET_FOOD_CATEGORY_BY_RESTAURANT_ID_SUCCESS";
export const GET_FOOD_CATEGORY_BY_RESTAURANT_ID_FAILURE = "GET_FOOD_CATEGORY_BY_RESTAURANT_ID_FAILURE";

export const GET_FOOD_CATEGORY_BY_SEARCH_REQUEST = "GET_FOOD_CATEGORY_BY_SEARCH_REQUEST";
export const GET_FOOD_CATEGORY_BY_SEARCH_SUCCESS = "GET_FOOD_CATEGORY_BY_SEARCH_SUCCESS";
export const GET_FOOD_CATEGORY_BY_SEARCH_FAILURE = "GET_FOOD_CATEGORY_BY_SEARCH_FAILURE";

export const DELETE_FOOD_CATEGORY_BY_ID_REQUEST = "DELETE_FOOD_CATEGORY_BY_ID_REQUEST";
export const DELETE_FOOD_CATEGORY_BY_ID_SUCCESS = "DELETE_FOOD_CATEGORY_BY_ID_SUCCESS";
export const DELETE_FOOD_CATEGORY_BY_ID_FAILURE = "DELETE_FOOD_CATEGORY_BY_ID_FAILURE";

export const UPDATE_FOOD_CATEGORY_BY_ID_REQUEST = "UPDATE_FOOD_CATEGORY_BY_ID_REQUEST";
export const UPDATE_FOOD_CATEGORY_BY_ID_SUCCESS = "UPDATE_FOOD_CATEGORY_BY_ID_SUCCESS";
export const UPDATE_FOOD_CATEGORY_BY_ID_FAILURE = "UPDATE_FOOD_CATEGORY_BY_ID_FAILURE";